#-Information---------------------------------------------------------------------------------------
name: analyzer
version: 1.1
target: sample
type: pipeline
recommendation: recommended
requires_db: True
description: >
  This preforms read based mapping against the resfinder, plasmidfinder and mlst DB's. The mlst DB's 
  are set via the species table in the mongoDB.
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
# None
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path
mlst_database_path: "/home/projects/ssi_10003/data/DB/ariba/mlst/"
abricate_resfinder_database: "/home/projects/ssi_10003/data/DB/abricate/resfinder_db/" 
abricate_plasmidfinder_database: "/home/projects/ssi_10003/data/DB/abricate/plasmidfinder_db/" 
ariba_resfinder_database: "/home/projects/ssi_10003/data/DB/ariba/resfinder_db/"
ariba_plasmidfinder_database: "/home/projects/ssi_10003/data/DB/ariba/plasmidfinder_db/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      species:
#---------------------------------------------------------------------------------------------------
