#-Information---------------------------------------------------------------------------------------
name: ssi_stamper
version: 1.2
target: sample
type: stamper
recommendation: required
requires_db: True
description: >
  This runs against the mondoDB database and certifies a sample that has run assemblatron and 
  whats_my_species on it's QC preformance (Core Facility/Supplying Lab/Ok). This can also be run
  as a script without output on the server (only bifrost DB)
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: "docker://kimleeng/bifrost-ssi_stamper:1.2"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
# None
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path
# None
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  components:
    assemblatron:
      status: Success
    whats_my_species:
      status: Success
#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  sample:
    stamps:
      stamp_list:
      ssi_stamper:
#---------------------------------------------------------------------------------------------------

