# Options
# -None

# --Required resource files--   
# relative to components folder (so ../../ to return to base snakemake folder) if not an absolute path
# -None

# Requirements for running component
requirements:
  components:
    assemblatron:
      status: Success
    whats_my_species:
      status: Success