# Input parameters with default values
sample_folder: "samples"
sample_sheet: "sample_sheet.xlsx"
partition: "standard"
grid: "slurm" # slurm|torque|none
assembly_with: "skesa" # skesa|spades
components: "whats_my_species,qcquickie,analyzer,assemblatron,testomatic" # available options are in components directory
group: "" # group for sbatch on torque system
use_mongodb: True 
run_type: "project" # run type (routine, project)
read_pattern: (?P<sample_name>.+?)(?P<sample_number>(_S[0-9]+)?)(?P<lane>(_L[0-9]+)?)_(?P<paired_read_number>R[1|2])(?P<set_number>(_[0-9]+)?)(?P<file_extension>\.fastq\.gz)
samples_to_ignore: ["Undetermined"]
memory: &memory 10 #in Gb
threads: &threads 5

# --Optional override values--  # if not set will look in resources folder for all files
#relative to samples components folder
adapters_fasta: "../resources/adapters.fasta"
# adapters_fasta: PATH/adapters.fasta     # fasta File
# run_name: NAME                              # if provided use that for db if not use folder
# mongo_db_key_location: PATH                 # location of keys.py used for accessing mongodb
kraken_database: "/srv/data/DB/kraken/minikraken_20171019_8GB/"   # Directory
kraken_kmer_dist: "/srv/data/DB/kraken/minikraken_20171019_8GB/minikraken_8GB_100mers_distrib.txt"  # TXT File
abricate_resfinder_database: "/srv/data/DB/abricate/resfinder_db/" # Directory
abricate_plasmidfinder_database: "/srv/data/DB/abricate/plasmidfinder_db/" # Directory
ariba_resfinder_database: "/srv/data/DB/ariba/resfinder/"
ariba_plasmidfinder_database: "/srv/data/DB/ariba/plasmidfinder/"
# MLST DB's is handled in species DB

# For processing sample sheets
samplesheet_column_mapping:
  sample_name: "SampleID"
  group: "SupplyingLab" 
  emails: "Initials"
  run_name: "ExperimentName"
  priority: "Priority"
  provided_species: "Organism" # a required name
