#-Basic info----------------------------------------------------------------------------------------
name: run_launcher
version: 2.0.5
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  schema_version: 2.0
  target: run
  type: pipeline
  recommendation: recommended
  description: >
    Processes a folder for running in bifrost
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://ssidk/bifrost-run_launcher:2.0.5"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  # For processing sample sheets
  samplesheet_column_mapping:
    sample_name: "SampleID"
    group: "SupplyingLab" 
    emails: "Initials"
    run_name: "ExperimentName"
    priority: "Priority"
    provided_species: "Organism" # a required name
    Comments: "Comments"
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
# None
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
# None
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  run:
    properties:
      mlst:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    results:
      cge_mlst/data_yaml: {}
  sample:
    _id: # sample creation
    name:
    properties:
      paired_reads:
        summary:
          data: # [String, String]
      sample_info:
        summary: 
          SampleID:
          provided_species:
          # Other columns in run_metadata.tsv
#---------------------------------------------------------------------------------------------------
