#-Basic info----------------------------------------------------------------------------------------
name: run_launcher
version: 2.0.5
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  schema_version: 2.0
  target: run
  type: pipeline
  recommendation: recommended
  description: >
    Processes a folder for running in bifrost
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://ssidk/bifrost-run_launcher:2.0.5"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  # These are all default values, a option can be provided to overwrite these
  run_folder: "samples"
  sample_sheet: "sample_sheet.xlsx"
  partition: "standard" # Default partition
  #force_partition: "outbreak" # Force a slurm partition
  #torque_node: # for use on specifying a torque node
  grid: "none" # slurm|torque|none
  walltime: "03:00:00"
  components: "min_read_check,whats_my_species,assemblatron,ssi_stamper" # available options are in components directory
  group: "" # group for sbatch on torque system
  use_mongodb: True 
  type: "project" # run type (routine, project)
  read_pattern: (?P<sample_name>.+?)(?P<sample_number>(_S[0-9]+)?)(?P<lane>(_L[0-9]+)?)_R(?P<paired_read_number>[1|2])(?P<set_number>(_[0-9]+)?)(?P<file_extension>\.fastq\.gz)
  samples_to_ignore: ["Undetermined"]
  # samples_to_include: null
  memory: &memory 10 #in Gb
  threads: &threads 4
  restart_times: 0
  init_only: False # initialize samples but don't run the components
  unlock: False # Run the components' snakemake in unlock mode (components wont run but will unlock directories)
  md5skip: False # set to True to skip md5sum update when recreating samples. Recommended: False
  #tmp_dir: "" # Run compute intensive steps on a scratch dir to avoid overdoing IO
  singularity_prefix: "/srv/data/tools/singularity/" 
  # --Optional override values--
  # run_name: NAME                              # if provided use that for db if not use folder

  # Path has to be absolute
  # DEPRECATED mongo_db_key_location: "/srv/data/tools/git.repositories/bifrost-private/resources/keys.txt"  # location of keys.py used for accessing mongodb (required for all components when using mongodb)
  # USE env var BIFROST_DB_KEY = "/srv/data/tools/git.repositories/bifrost-private/resources/keys.txt"


  # MLST DB's is handled in species DB

  # For processing sample sheets
  samplesheet_column_mapping:
    sample_name: "SampleID"
    group: "SupplyingLab" 
    emails: "Initials"
    run_name: "ExperimentName"
    priority: "Priority"
    provided_species: "Organism" # a required name
    Comments: "Comments"

  priority_mapping:
    high: "outbreak"
    low: "daytime"

#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
# None
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
# None
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  run:
    properties:
      mlst:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    results:
      cge_mlst/data_yaml: {}
  sample:
    _id: # sample creation
    name:
    properties:
      datafiles:
        summary:
          paired_reads: # [String, String]
      sample_info:
        summary: 
          SampleID:
          provided_species:
          # Other columns in run_metadata.tsv
#---------------------------------------------------------------------------------------------------
