#-Information---------------------------------------------------------------------------------------
name: ariba_plasmidfinder
version: 1.1
target: sample
type: pipeline
recommendation: recommended
description: >
  This preforms read based mapping against the plasmidfinder DB's. 
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
# -None
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path
abricate_plasmidfinder_database: "resources/abricate_plasmidfinder_db" 
ariba_plasmidfinder_database: "resources/ariba_plasmidfinder_db"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    reads:
      R1:
      R2:
#-DB Value changes (excluding component output)-----------------------------------------------------
# None
#---------------------------------------------------------------------------------------------------
