#-Information---------------------------------------------------------------------------------------
name: whats_my_species
category: &category Species Detection
version: 2.0
schema_version: 2.0
target: sample
type: pipeline
recommendation: required
description: >
  This runs kraken/bracken on a sample in order to determine the species found in the sample. Reads
  are first filtered using bbduk. The species is then set for the sample from this.
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://ssidk/bifrost-whats_my_species:2.0"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
kraken_database: "/bifrost_resources/minikraken/"
kraken_kmer_dist: "/bifrost_resources/minikraken_4GB_100mers_distrib.txt"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    reads:
      R1:
      R2:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files:
    - whats_my_species/kraken_report.txt
    - whats_my_species/bracken.txt
    - whats_my_species/kraken_report_bracken.txt
  sample:
    properties:
      species:
      species_detection:
        summary: #see sample_component summary
        component:
          _id: "ObjectId"
          date: "datetime"
    report:
  sample_component:
    summary:
      percent_unclassified:
      percent_classified_species_1:
      name_classified_species_1:
      percent_classified_species_2:
      name_classified_species_2 :
      detected_species:
#---------------------------------------------------------------------------------------------------

