#-Information---------------------------------------------------------------------------------------
name: min_read_check
category: &category Size Check
version: 2.0
schema_version: 2.0
target: sample
type: pipeline
recommendation: recommended
description: >
  Checks that there's a minimum number of reads after trimming to run.
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://ssidk/bifrost-min_read_check:1.0"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  min_num_reads: 10000
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path.
# Note paths are set up to the absolute locations in the docker container, if you want 
# to overwrite these values be sure to mount the src folder to the docker image
adapters_fasta: "/bifrost_resources/adapters.fasta"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    reads:
      R1:
      R2:
#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  sample:
    properties:
      size_check:
        component:
          _id: "ObjectId"
          _date: "datetime"
    reporter:
  sample_component:
    summary:
      has_min_num_of_reads: # Boolean
#---------------------------------------------------------------------------------------------------
